### ISSUE TITLE
[Sound schemes submission] Created Discord, Five Nights at Freddy's 1 and Geometry Dash sound themes

### ISSUE THREAD

**Issue by TheInsane101** [ORelio/Sound-Manager-Schemes#11]
Sorry, IDK how to use Github, so I posted them to Drive with a link. The Geometry Dash theme was made with the help of another person, RealMattLmao. 

Author fields credit the original sources of the sound effects before mentioning who ported them over to SM. GD and FNAF 1 themes will likely fall under the Games category, but you decide where Discord will fall under.

Hope these are suitable and worthy of adding! :) https://drive.google.com/drive/folders/1YNexrgOJYCMlU64b5hR28SEyhcdUqo4-?usp=sharing

Btw wouldn't it be prefferred to add flairs differentiating "Issues" submissions into scheme posts and actual issue posts?

**Comment by ORelio** [comment]
Thanks for contributing! I'll review your schemes ASAP!

> Sorry, IDK how to use Github, so I posted them to Drive with a link.

Don't worry, I'll add your schemes to the repository manually 🙂

> you decide where Discord will fall under.

I'll probably sort it under "Misc." for now, since there are no applicable category yet.

> Btw wouldn't it be prefferred to add flairs differentiating "Issues" submissions into scheme posts and actual issue posts?

Actual submissions are usually identified as "Pull requests". This involve creating a fork (copy) of the repository under your own account, then add the scheme to your fork, and click on the button shown in your fork to propose the changes in a "pull request" for addition into this repository. Your submission would appear under the "Pull request" tab.

**Comment by TheInsane101** [comment]
Thank you for your explanations! I might make and post schemes for FNAF 2 - 6 later!

And maybe horrible voice covers/acappella of the Windows sounds attempted by me lol
Or Minecraft Noteblock recreations of the Windows sounds, but I'd have to make those sounds from scratch first...

**Comment by ORelio** [comment]
Have fun! I've been pretty busy but will add your schemes ASAP. Reviewed them quickly, they are good for adding :+1:

**Comment by TheInsane101** [comment]
Thank you! And take your time with the adding; don't stress or rush at all!

**Comment by ORelio** [comment]
Added your sound schemes to the repository, Discord went to the Abstract category. Feel free to reopen this issue or add a new one to share more schemes 👍
