### ISSUE TITLE
Microsoft Defender flags a virus??

### ISSUE THREAD

**Issue by Skrell** [ORelio/Sound-Manager-Schemes#8]
![image](https://github.com/ORelio/Sound-Manager-Schemes/assets/590266/e22e1b2e-6950-49ac-aa37-b96b4d87785b)

**Comment by ORelio** [comment]
Hi @Skrell,

This really looks like a false positive because the Schemes repository does not even contain executable code. All sound schemes are Zip files containing audio files, one image, and one text file with some info about the scheme.

If the Zip file gets incorrectly flagged on your computer, you can try downloading as. tar.gz then unzipping with 7-Zip or winRAR, or use the DownloadSchemes tool provided along with SoundManager and selecting everything to download all the schemes.

**Comment by ORelio** [comment]
Could not reproduce using the "Download ZIP" feature from Github on a Windows PC with fully updated Microsoft Defender.

**Comment by ORelio** [comment]
Could not reproduce using the "Download ZIP" feature from Github on a Windows PC with fully updated Microsoft Defender.
